{"name": "test_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 17 == 16\n +  where 16 = add(9, 7)", "trace": "self = <scripts.test_add_1.TestAdd object at 0x000001E20B713A40>\n\n    def test_3(self):\n        print('9, 7, 16 用例通过')\n>       assert 17 == add(9, 7)\nE       assert 17 == 16\nE        +  where 16 = add(9, 7)\n\nscripts\\test_add_1.py:35: AssertionError"}, "start": 1747049122680, "stop": 1747049122681, "uuid": "0bf6c609-61ac-455f-b837-b55443ac7571", "historyId": "310535c75805d52dbd30af903a5b9f42", "testCaseId": "310535c75805d52dbd30af903a5b9f42", "fullName": "scripts.test_add_1.TestAdd#test_3", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_add_1"}, {"name": "subSuite", "value": "TestAdd"}, {"name": "host", "value": "DESKTOP-4NDO5KD"}, {"name": "thread", "value": "28812-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_add_1"}]}